image:
  repository: rucio/rucio-server
  tag: release-1.27.1
  pullPolicy: IfNotPresent

replicaCount: 1
authReplicaCount: 1
traceReplicaCount: 1

httpd_config:
  encoded_slashes: "True"
ingress:
  tls: 
    - secretName: rucio-server.tls-secret

