apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rucio-sense-xrd-vol
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
