apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: NAME_PLACEHOLDER
  name: NAME_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: NAME_PLACEHOLDER
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: NAME_PLACEHOLDER
    spec:
      hostNetwork: True
      hostPID: True
      containers:
        - env:
          - name: OSG_FQDN
            value: IPV6_PLACEHOLDER
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: jguiang/rucio-sense-xrootd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: PORT_PLACEHOLDER
          name: NAME_PLACEHOLDER
          securityContext:
            privileged: True
          resources:
            limits:
              cpu: 8
              memory: 10Gi
            requests:
              cpu: 4
              memory: 4Gi
          volumeMounts:
            - mountPath: /rucio
              name: cache-volume
            - mountPath: /rucio/SITE_PLACEHOLDER.file
              name: conf
              subPath: test.file
            - mountPath: /etc/xrootd/xrootd.cfg
              name: conf
              subPath: xrootd.cfg
            - mountPath: /etc/grid-security/hostcert.pem
              name: certs
              subPath: hostcert.pem
            - mountPath: /etc/grid-security/hostkey.pem
              name: certs
              subPath: hostcert.key.pem
      nodeSelector:
        kubernetes.io/hostname: NODE_PLACEHOLDER
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: cache-volume
          hostPath:
            path: HOST_DIR_PLACEHOLDER
            type: Directory
        - name: certs
          secret:
            secretName: NAME_PLACEHOLDER-self-certs
            items:
              - key: hostcert.pem
                path: hostcert.pem
              - key: hostcert.key.pem
                path: hostcert.key.pem
            defaultMode: 0644
        - name: conf
          configMap: 
            name: NAME_PLACEHOLDER-conf
            items:
              - key: xrootd.cfg
                path: xrootd.cfg
              - key: test.file
                path: test.file
        - name: supervisor
          configMap: 
            name: NAME_PLACEHOLDER-supervisor
            items:
              - key: supervisord.conf
                path: supervisord.conf
