resources:
  - deploy.yaml

configMapGenerator:
  - name: NAME_PLACEHOLDER-conf
    files:
      - xrootd.cfg
      - test.file
  - name: NAME_PLACEHOLDER-supervisor
    files:
      - supervisord.conf

secretGenerator:
  - name: NAME_PLACEHOLDER-self-certs
    files:
      - hostcert.pem
      - hostcert.key.pem

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: NAME_PLACEHOLDER
