apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: rucio
  name: rucio
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rucio
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: rucio
    spec:
      hostNetwork: True
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "rucio"
        - "ruciodb"
        - "graphite"
        - "minio"
      - ip: "132.249.252.252"
        hostnames:
        - "fts"
        - "ftsdb"
      containers:
      # Rucio
      - name: rucio
        image: docker.io/jguiang/rucio-dev:latest
        imagePullPolicy: Always
        env:
        - name: X509_USER_CERT
          value: /opt/rucio/etc/usercert.pem
        - name: X509_USER_KEY
          value: /opt/rucio/etc/userkey.pem
        - name: RDBMS
          value: postgres11
        ports:
        - containerPort: 443
        resources:
          limits:
            cpu: 24
            memory: 24Gi
          requests:
            cpu: 14
            memory: 10Gi
        volumeMounts:
        - mountPath: /opt/rucio/lib
          name: rucio-lib
        - mountPath: /opt/rucio/tools
          name: rucio-tools
        - mountPath: /opt/rucio/bin
          name: rucio-bin
        - mountPath: /opt/dmm
          name: dmm
        - mountPath: /etc/grid-security/hostcert.pem
          name: real-certs-hostcert
        - mountPath: /etc/grid-security/hostkey.pem
          name: real-certs-hostkey
        - mountPath: /opt/rucio/etc/usercert.pem
          name: real-certs-hostcert
        - mountPath: /opt/rucio/etc/userkey.pem
          name: real-certs-hostkey
        - mountPath: /opt/rucio/etc/usercertkey.pem
          name: real-certs-hostcertkey
        - mountPath: /etc/grid-security/certificates/5fca1cb1.0
          name: certs
          subPath: rucio_ca.pem
        - mountPath: /root/.sense-o-auth.yaml
          name: certs
          subPath: .sense-o-auth.yaml
      # Rucio DB
      - name: ruciodb
        image: docker.io/postgres:11
        imagePullPolicy: Always
        args: ["-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
        env:
        - name: POSTGRES_USER
          value: rucio
        - name: POSTGRES_DB
          value: rucio
        - name: POSTGRES_PASSWORD
          value: secret
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 24
            memory: 16Gi
          requests:
            cpu: 4
            memory: 8Gi
      # Graphite
      - name: graphite
        image: docker.io/graphiteapp/graphite-statsd
        imagePullPolicy: Always
        ports:
        - containerPort: 8125
        resources:
          limits:
            cpu: 4
            memory: 16Gi
          requests:
            cpu: 1
            memory: 1Gi
      # Minio
      - name: minio
        image: docker.io/minio/minio
        imagePullPolicy: Always
        args: ["server", "/data"]
        env:
        - name: MINIO_ACCESS_KEY
          value: admin
        - name: MINIO_SECRET_KEY
          value: password
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: 4
            memory: 16Gi
          requests:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - mountPath: /root/.minio/certs/public.crt
          name: certs
          subPath: hostcert_minio.pem
        - mountPath: /root/.minio/certs/private.key
          name: certs
          subPath: hostcert_minio.key.pem
      nodeSelector:
        kubernetes.io/hostname: rucio-sense.t2.ucsd.edu
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rucio-lib
        hostPath:
          path: /home/aaarora/rucio/lib
          type: Directory
      - name: rucio-tools
        hostPath:
          path: /home/aaarora/rucio/tools
          type: Directory
      - name: rucio-bin
        hostPath:
          path: /home/aaarora/rucio/bin
          type: Directory
      - name: dmm
        hostPath:
          path: /home/aaarora/dmm/
          type: Directory
      - name: real-certs-hostcert
        hostPath:
          path: /home/aaarora/certs/hostcert.pem
          type: File
      - name: real-certs-hostkey
        hostPath:
          path: /home/aaarora/certs/hostkey.pem
          type: File
      - name: real-certs-hostcertkey
        hostPath:
          path: /home/aaarora/certs/hostcertkey.pem
          type: File
      - name: certs
        secret:
          secretName: rucio-self-certs
          items:
          - key: rucio_ca.pem
            path: rucio_ca.pem
          - key: hostcert_minio.pem
            path: hostcert_minio.pem
          - key: hostcert_minio.key.pem
            path: hostcert_minio.key.pem
          - key: .sense-o-auth.yaml
            path: .sense-o-auth.yaml
          defaultMode: 0644
