resources:
  - deploy-rucio.yaml
  #- deploy-fts.yaml

secretGenerator:
  - name: rucio-self-certs
    files:
      - certs/rucio_ca.pem
      - certs/hostcert_fts.pem
      - certs/hostcert_fts.key.pem
      - certs/hostcert_minio.pem
      - certs/hostcert_minio.key.pem
      - certs/.sense-o-auth.yaml
      - certs/dummykey
      - fts3config

generatorOptions:
  disableNameSuffixHash: true
