resources:
  - deploy-rucio.yaml
  - deploy-fts.yaml

secretGenerator:
  - name: rucio-self-certs
    files:
      - certs/hostcert_rucio.pem
      - certs/hostcert_rucio.key.pem
      - certs/ruciouser.pem
      - certs/ruciouser.key.pem
      - certs/ruciousercertkey.pem
      - certs/rucio_ca.pem
      - certs/hostcert_fts.pem
      - certs/hostcert_fts.key.pem
      - certs/hostcert_minio.pem
      - certs/hostcert_minio.key.pem
      - certs/.sense-o-auth.yaml
      - certs/dummykey

generatorOptions:
  disableNameSuffixHash: true
