apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: NAME_PLACEHOLDER
  name: NAME_PLACEHOLDER
spec:
  selector:
    matchLabels:
      k8s-app: NAME_PLACEHOLDER
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: NAME_PLACEHOLDER
    spec:
      hostNetwork: True
      containers:
        - env:
          - name: OSG_FQDN
            value: IPV6_PLACEHOLDER
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: jguiang/us-cms-datalake-cluster:latest
          imagePullPolicy: Always
          ports:
            - containerPort: MAIN_PORT_PLACEHOLDER
            - containerPort: REDI_PORT_PLACEHOLDER
          name: NAME_PLACEHOLDER
          securityContext:
            privileged: True
          resources:
            limits:
              cpu: 20
              memory: 20Gi
            requests:
              cpu: 2
              memory: 2Gi
          volumeMounts:
            - mountPath: /mnt
              name: ephemeral
            - mountPath: /etc/xrootd/xrootd.cfg
              name: conf
              subPath: xrootd.cfg
            - mountPath: /etc/xrootd/auth-file
              name: conf
              subPath: auth-file
            - mountPath: /etc/supervisord.d/10-xrootd.conf
              name: supervisor
              subPath: supervisord.conf
            - mountPath: /etc/grid-security/grid-mapfile
              name: conf
              subPath: grid-mapfile
            - mountPath: /etc/grid-security/certificates/5fca1cb1.0
              name: conf
              subPath: 5fca1cb1.0
            - mountPath: /etc/grid-security/certificates/5fca1cb1.signing_policy
              name: conf
              subPath: 5fca1cb1.signing_policy
            - mountPath: /etc/grid-security/hostcert.pem
              name: certs
              subPath: hostcert.pem
            - mountPath: /etc/grid-security/hostkey.pem
              name: certs
              subPath: hostcert.key.pem
      nodeSelector:
        kubernetes.io/hostname: NODE_PLACEHOLDER
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: ephemeral
          emptyDir: {}
        - name: certs
          secret:
            secretName: NAME_PLACEHOLDER-self-certs
            items:
              - key: hostcert.pem
                path: hostcert.pem
              - key: hostcert.key.pem
                path: hostcert.key.pem
            defaultMode: 0644
        - name: conf
          configMap: 
            name: NAME_PLACEHOLDER-conf
            items:
              - key: xrootd.cfg
                path: xrootd.cfg
              - key: grid-mapfile
                path: grid-mapfile
              - key: auth-file
                path: auth-file
              - key: 5fca1cb1.0
                path: 5fca1cb1.0
              - key: 5fca1cb1.signing_policy
                path: 5fca1cb1.signing_policy
        - name: supervisor
          configMap: 
            name: NAME_PLACEHOLDER-supervisor
            items:
              - key: supervisord.conf
                path: supervisord.conf
