apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: nonsense
  name: nonsense
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nonsense
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: nonsense
    spec:
      # tolerations:
      # - key: "nautilus.io/nsi"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # - key: "node.kubernetes.io/unreachable"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      hostNetwork: True
      containers:
        - image: jguiang/nonsense:latest
          command: [ "flask", "run" ]
          imagePullPolicy: Always
          env:
            - name: FLASK_RUN_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 5000
          name: nonsense
          securityContext:
            privileged: True
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 2Gi
      nodeSelector:
        # kubernetes.io/hostname: k8s-gen4-01.sdsc.optiputer.net
        # kubernetes.io/hostname: k8s-gen4-07.ultralight.org
        # kubernetes.io/hostname: dtn138.sl.startap.net
        # kubernetes.io/hostname: nrp-02.nrp-nautilus.io
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
