apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: nonsense
  name: nonsense
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nonsense
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: nonsense
    spec:
      hostNetwork: True
      containers:
        - image: jguiang/nonsense:latest
          command: [ "flask", "run" ]
          imagePullPolicy: Always
          env:
            - name: FLASK_RUN_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 5000
          name: nonsense
          securityContext:
            privileged: True
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 2Gi
      nodeSelector:
        kubernetes.io/hostname: river-c032.ssl-hep.org
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
